name: Main

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "*.md"
      - ".gitignore"
      - "LICENSE"
    branches:
      - master
    tags:
      - "**"
  pull_request:
    paths-ignore:
      - "*.md"
      - ".gitignore"
      - "LICENSE"
    branches:
      - master

jobs:
  lint:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
        shell: bash
      - run: make lint

  test:
    needs: [lint]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install podman 4.2.0
        run: |
          sudo bash -c 'echo "deb [trusted=yes] http://ftp.us.debian.org/debian/ experimental main" >> /etc/apt/sources.list.d/experimental.list'
          sudo apt -y update
          sudo apt -y install podman=4.2.0+ds1-3
      - name: Start podman
        run: |
          systemctl restart --user podman
          systemctl restart --user podman.socket
      - name: Test
        run: |
          podman pull ubuntu:latest
          PODMAN_API_URI="unix:///run/user/$UID/podman/podman.sock" make test
